### ISSUE TITLE
Build failure in VS2017 (warning C4530)

### ISSUE THREAD

**Issue by benkaraban** [Blizzard/s2client-api#132]
I followed the instructions in docs/building.md but when building in VS2017 Community Edition, I got a large number of _"warning C4530: C++ exception handler used, but unwind semantics are not enabled"_ in the sc2* projects.

And since warnings are treated as errors, the build failed.

I was able to fix this by adding this line at the right place in CMakeLists.txt:
`    set(CMAKE_CXX_FLAGS "/EHsc" CACHE STRING "" FORCE)`

But I'm not sure if this is a problem with my own setup or with the project itself?

**Comment by kuzi117** [comment]
I'm not sure about your issue, but I did want to point out that you've effectively removed all cxx flags except for the one you set the since the command overwrites the flags. Try "/EHsc ${CMAKE_CXX_FLAGS}" to concatenate it and to make sure that removing a flag also want the solution. Also using cache and force seems unneeded to me, I've modified cxx flags without those before. Was it not working without them!

**Comment by AnthonyBrunasso** [comment]
We use 2017 professional in the office and believe have at least tested for a clean compile with the community edition. I can try again again with the community edition when I get in today.

**Comment by benkaraban** [comment]
You can forget about this. I've regenerated everything from scratch on a fresh clone and it worked fine.

The first time I launched CMake, I was missing some VS components and needed to rerun it after the VS installer. I _guess_ CMake's first run left some intermediate files that confused it when run for the second time.

In any way, this was indeed a quirk on my side and not a problem with the project.

Sorry for the noise and thanks for the support.

**Comment by AnthonyBrunasso** [comment]
Oh that's great to hear! Thanks for letting me know.
